fix: reset the quote when the source token matches the destination token
rango-exchange/rango-client pull request #486
Opened 2023-12-27 18:42 UTC by Ikari-Shinji-re

# Summary

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# How did you test this change?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

2023-12-30 09:05 UTC, samobasquiat requested changes

2023-12-30 09:05 UTC, samobasquiat commented on widget/embedded/src/components/HeaderButtons/HomeButtons.tsx
> +          <div>
I fixed it in another way.
what do you think?
https://github.com/rango-exchange/rango-client/pull/488/files

2023-12-31 06:05 UTC, samobasquiat approved these changes

2023-12-31 09:21 UTC, RanGojo approved these changes

2023-12-31 09:23 UTC, merged