fix: persist language in store
rango-exchange/rango-client pull request #498
Opened 2024-01-01 19:33 UTC by nikaaru

# Summary

When navigating to a new route language restore to the default (En).
this issue was fixed by persistent language in the store.

# Checklist:

- [ ] I have performed a self-review of my code

2024-01-03 10:41 UTC, mikasackermn requested changes

2024-01-03 10:41 UTC, mikasackermn commented on widget/embedded/src/containers/App/App.tsx
> -    changeLanguage(config?.language);
It is impossible to alter the playground's language. Please review this line of code as it relates to it.

2024-01-07 06:36 UTC, mikasackermn approved these changes

2024-01-08 05:24 UTC, Ikari-Shinji-re commented on widget/embedded/src/hooks/useLanguage.ts
> +    activeLanguage: language || defaultLanguage,
I believe that if the language in the configuration changes, the language of the widget should also change and take precedence over both the default and user-selected values. Currently, when a user selects a language in the widget, the widget configuration is unable to impact the language. I suggest aligning the behavior with the token selection behavior for a more desirable outcome.

2024-01-08 09:54 UTC, Ikari-Shinji-re approved these changes

2024-01-08 10:01 UTC, merged