add sort filter for multi routing (compact mode)
rango-exchange/rango-client pull request #592
Opened 2024-02-18 08:29 UTC by mikasackermn

# Summary

User could change sort preference in routes page.
(Added sort filter for multi routing)

Fixes # (issue)

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

2024-02-21 09:25 UTC, yeager-eren requested changes
Thanks. I reviewed your PR, in addition to comments I put, these two items has been missed:

1. Hover on items hasn't been implemented
2. On dark mode, hovering on select has a white color.

2024-02-24 08:04 UTC, mikasackermn commented on widget/ui/src/components/Select/Select.types.ts
> +  value?: Item;
fixed

2024-02-24 08:08 UTC, mikasackermn commented on widget/ui/src/components/Select/select.styles.ts
> +    '@xs': {
This was before, when we were going to use select on the first page, in the size of 375 px was messed up. We don't need it now.

2024-02-24 09:17 UTC, yeager-eren approved these changes
Thanks. lgtm.

2024-02-24 10:13 UTC, merged