feat: implement expanded-mode route
rango-exchange/rango-client pull request #596
Opened 2024-02-19 13:30 UTC by samobasquiat

# Summary

Implemented expanded-mode route.
It doesn't have a loading state & and a hover for each step yet.
And its dark theme might be changed. 

# How did you test this change?

It can be tested in the storybook.
For testing dark mode in the storybook, you can change the `defaultValue` of `globalTypes` 
Or you can easily pass `darkTheme` as a `storyTheme` in `withTheme`
both in in `widget/ui/.storybook/preview.tsx`

# Checklist:

- [x] I have performed a self-review of my code
- [x] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

2024-02-20 07:51 UTC, RanGojo requested changes

2024-02-20 07:51 UTC, RanGojo commented on widget/ui/src/components/TagRoute/index.ts
> +export { TagRoute } from './TagRoute';
You could change it to `QuoteTag`

2024-02-20 07:51 UTC, RanGojo commented on widget/ui/src/components/ExpandedRoute/ExpandedRoute.types.ts
> +  outputPrice: SwapInputProps['price'];
I'm not sure. Isn't better to move this component to widget embedded component and just pass `quote: SelectedQuote` as a props?

```
export interface PropTypes {
  quote: SelectedQuote
  tooltipContainer?: HTMLElement;
  onClick?: () => void;
  selected?: boolean;
}
```

2024-02-20 07:51 UTC, RanGojo commented on widget/ui/src/components/ExpandedRoute/ExpandedRoute.tsx
> +export function ExpandedRoute(props: PropTypes) {
Please double check if you handle step warning/error case.

<img width="307" alt="Screenshot 2024-02-20 at 10 37 49" src="https://github.com/rango-exchange/rango-client/assets/99180934/2a9b9a49-cb23-4145-8981-9607e24e29a3">

<img width="521" alt="Screenshot 2024-02-20 at 10 37 31" src="https://github.com/rango-exchange/rango-client/assets/99180934/375f0f30-92ce-4c3b-bc83-3bf20bc658de">

2024-02-21 10:04 UTC, nikaaru commented
![image](https://github.com/rango-exchange/rango-client/assets/141495369/f2ac91b3-1b35-4520-912c-523976793d89)

small size seems to be correct instead of xmedium

2024-02-21 10:10 UTC, nikaaru commented
![image](https://github.com/rango-exchange/rango-client/assets/141495369/5810fff5-328f-44b1-be8a-fb06285cd3c3)

It seems that some text sizes are not correct.

2024-02-21 10:13 UTC, nikaaru commented
![image](https://github.com/rango-exchange/rango-client/assets/141495369/ecf03754-3898-4592-b0d4-65ea3e92a143)
The color in the parentheses does not match the figma

2024-02-21 10:48 UTC, nikaaru commented
![image](https://github.com/rango-exchange/rango-client/assets/141495369/9bf56ecd-1857-49d3-b56e-9877adbbab6e)
The color of the error icon does not match the figma

2024-02-21 10:59 UTC, nikaaru commented on widget/embedded/src/components/Quote/Quote.tsx
> +const GAS_FEE_MAX = 30;
NIT:  I think it is better to be in this file: src/constants/quote.ts

2024-02-21 10:59 UTC, nikaaru commented on widget/embedded/src/pages/Routes.tsx
> +  useEffect(() => {
To remind

2024-02-21 10:59 UTC, nikaaru commented on widget/ui/src/components/ExpandedRoute/ExpandedRoute.tsx
> +import { ErrorIcon, WarningIcon } from 'src/icons';
When run storybook (yarn dev:ui), 
we have this error:
Error: Cannot find module 'src/icons'

2024-02-21 12:27 UTC, nikaaru approved these changes

2024-02-21 13:25 UTC, merged