feat: add test to check workflow
rango-exchange/rango-client pull request #687
Opened 2024-04-22 09:58 UTC by nikaaru

# Summary

Running project tests was also added to the check workflow.
From now on, for each PR that is opened, in addition to the conventional commit, test files are also run, and if all tests pass, the check workflow is confirmed.

Also, before running the tests, we build all the libraries, and in the build process, the types are also checked, to make sure that all the libraries work correctly.

# How did you test this change?

To test, you can get a new branch from this branch.
And open a new PR and see the new check workflow processes, i.e. building projects and running tests.

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

2024-04-23 16:20 UTC, yeager-eren requested changes

2024-04-24 09:27 UTC, nikaaru commented on scripts/common/utils.mjs
> +  const result = JSON.parse(JSON.parse(stdout).data) ;
Done

2024-04-24 09:28 UTC, nikaaru commented on scripts/build-libs/command.mjs
> +  console.log('these packages will be build:', packagesToBeBuild.map(pkg=>pkg.name).join(', ')) ;
Fixed

2024-04-24 10:02 UTC, yeager-eren approved these changes
lgtm

2024-04-24 10:03 UTC, merged