!WIP fix: sync notifications with persisted swaps
rango-exchange/rango-client pull request #694
Opened 2024-04-27 06:14 UTC by Ikari-Shinji-re

# Summary

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# How did you test this change?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

2024-05-19 11:50 UTC, nikaaru commented on widget/embedded/src/store/notification.ts
> +  isSynced: boolean;
can we remove isSynced?

2024-05-19 11:50 UTC, nikaaru commented on widget/embedded/src/store/notification.ts
>    setAsRead: (requestId: Notification['requestId']) => void;
I think it is better to change `setAsRead` to `removeNotification`.
and remove the read property from the Notification type.

2024-05-19 11:50 UTC, nikaaru commented on widget/embedded/src/store/notification.ts
>    getUnreadNotifications: () => Notification[];
Also we can change `getUnreadNotifications` to `getNotification`.

2024-05-19 11:50 UTC, nikaaru commented on widget/embedded/src/store/notification.ts
> +            const notifications: Notification[] = [];
This function can be very simple to clear only the notification.
(remove `isSwapFinished` from this logic)

2024-05-19 11:50 UTC, nikaaru commented on widget/embedded/src/store/notification.ts
> +          if (isSynced) {
Can we remove `isSynced` from getting notification functionality?

2024-05-20 11:26 UTC, nikaaru approved these changes
Thanks,
LGTM

2024-05-20 11:33 UTC, nikaaru commented on widget/embedded/src/store/notification.ts
> +        migrate: (persistedState, version) => {
It was interesting
good job

2024-05-21 05:29 UTC, RyukTheCoder commented on widget/embedded/src/hooks/useSyncNotifications/useSyncNotifications.ts
> +  const shouldSyncNotifications =
Currently this code runs in every render and in result of that, 'syncNotifications' runs in every render which seems to be an expensive function. Is this the proper behavior?

2024-05-21 08:20 UTC, Ikari-Shinji-re commented on widget/embedded/src/store/notification.ts
> +          if (version === 0) {
Previously, we stored all notifications in the local storage, regardless of whether they were read or unread. Each notification had a property called "read". However, this approach is no longer necessary. To synchronize the user's persisted data in the local storage with the current version, we are considering implementing a migration process. It's important to retain this code for the time being. If we introduce further changes to the structure of this storage in the future, we may adjust this migration to ensure that user storage is updated to the latest version accordingly.

2024-05-21 08:52 UTC, RyukTheCoder requested changes

2024-05-21 08:52 UTC, RyukTheCoder commented on widget/embedded/src/hooks/useSyncNotifications/useSyncNotifications.ts
> +export function useSyncNotifications() {
```suggestion
export function useSyncNotifications() {
  const { isSynced, syncNotifications } = useNotificationStore();
  const { manager, state } = useManager();

  useEffect(() => {
    const shouldSyncNotifications =
      useNotificationStore.persist.hasHydrated() &&
      state.loadedFromPersistor &&
      !isSynced;

    if (shouldSyncNotifications) {
      syncNotifications(getPendingSwaps(manager));
    }
  }, [
    useNotificationStore.persist.hasHydrated(),
    state.loadedFromPersistor,
    isSynced,
  ]);
}
```

2024-05-21 08:52 UTC, RyukTheCoder commented on widget/embedded/src/hooks/useSyncNotifications/useSyncNotifications.ts
> +export function useSyncNotifications() {
Thanks. Please check this suggestion.

2024-05-21 09:04 UTC, RyukTheCoder approved these changes
LGTM

2024-05-27 09:07 UTC, merged