feat: migrate storybook components to new package
rango-exchange/rango-client pull request #698
Opened 2024-04-28 00:53 UTC by mikasackermn

# Summary

We have some components that has stroybook, they need to be moved to /storybook from /ui package.

Checklist:

- [ ] Move .stories files
- [ ] Update imports
- [ ] Move mock files, if there is any.

Fixes # (issue)

# Checklist:

- [ ] I have performed a self-review of my code

2024-04-30 12:32 UTC, samobasquiat requested changes

2024-04-30 12:32 UTC, samobasquiat commented on widget/storybook/src/containers/ConnectWalletsModal/mock.ts
> +    image: 'https://app.rango.exchange/wallets/coinbase.svg',
It's not related to this PR but this Url doesn't work anymore.
```suggestion
    image: 'https://raw.githubusercontent.com/rango-exchange/assets/main/wallets/coinbase/icon.svg,
```

2024-05-01 12:03 UTC, samobasquiat approved these changes

2024-05-06 17:19 UTC, nikaaru approved these changes
LGTM

2024-05-07 12:09 UTC, merged