feat: display all notifications in the notification popover
rango-exchange/rango-client pull request #758
Opened 2024-06-02 12:23 UTC by Ikari-Shinji-re

# Summary

Moving the notifications components to the UI package for use in the `widget-embedded` and `Dapp`. Display all notifications without limitations; it can be scrollable.

# Checklist:

- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

2024-06-02 13:01 UTC, RyukTheCoder requested changes
Thanks, I just added two minor comments

2024-06-02 13:01 UTC, RyukTheCoder commented on widget/embedded/src/utils/meta.ts
> +  return blockchains.find((blockchain) => blockchain.name === blockchainName)
iterating over all blockchains can be expensive specially when using it in the list of notifications which can contain several items. Can you please create a map of blockchains name and logo and use that instead.

2024-06-02 13:01 UTC, RyukTheCoder commented on widget/ui/src/containers/Notifications/NotificationNotFound.tsx
> +import { Divider, Typography } from '../../../src/components';
```suggestion
import { Divider, Typography } from 'src/components';
```

2024-06-02 13:12 UTC, RyukTheCoder commented on widget/embedded/src/utils/meta.ts
> +  return blockchains.find((blockchain) => blockchain.name === blockchainName)
This type of performance improvements will be done in another task

2024-06-02 13:38 UTC, RyukTheCoder approved these changes
LGTM

2024-06-18 06:41 UTC, mikasackermn approved these changes
LGTM

2024-06-23 13:55 UTC, merged