feat: implement sign message method for providers with a custom signer
rango-exchange/rango-client pull request #807
Opened 2024-07-22 07:12 UTC by Ikari-Shinji-re

# Summary

Some providers have implemented a custom signer instead of using the base signers/implementations. We need to implement the `signMessage` method for these providers.

# How did you test this change?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Implemented a user interface (UI) change, referencing our Figma design to ensure pixel-perfect precision.

2024-07-30 11:27 UTC, mikasackermn approved these changes

2024-08-07 08:48 UTC, RanGojo approved these changes

2024-08-07 09:18 UTC, RanGojo requested changes

2024-08-07 09:18 UTC, RanGojo commented on signers/signer-solana/package.json
> +    "@rango-dev/wallets-shared": "^0.35.1",
Please remove dependency to wallet shared for Solana signer. Signers should work independently.

2024-08-07 09:18 UTC, RanGojo commented on signers/signer-terra/package.json
> +    "@rango-dev/wallets-shared": "^0.35.1",
also here.

2024-08-07 10:04 UTC, RanGojo approved these changes

2024-08-10 06:46 UTC, merged