chore: improve warning messages and titles
rango-exchange/rango-client pull request #883
Opened 2024-09-24 09:00 UTC by RanGojo

# Summary

In this PR, I've updated warning messages in widget.

Fixes # (issue)

# How did you test this change?

By checking related section specially adding experimental chain.

# Checklist:

- [x] I have performed a self-review of my code

2024-09-24 10:30 UTC, RyukTheCoder requested changes
Tnx, I just added some minor comments.

2024-09-24 10:30 UTC, RyukTheCoder commented on widget/embedded/src/components/Slippage/SlippageTooltipContent.tsx
> +          'This setting is applied to each individual step (e.g. 1Inch, Thorchain, etc.), meaning only that specific step will be reverted, not the entire route.'
```suggestion
          'This setting is applied to each step (e.g. 1Inch, Thorchain, etc.), meaning only that specific step will be reverted, not the entire route.'
```
Redundant

2024-09-24 10:30 UTC, RyukTheCoder commented on widget/embedded/src/pages/LanguagePage.tsx
> +          title="Warning: We are using machine translation, so the translations may not be very accurate."
```suggestion
          title="Warning: We are using machine translation, so the translations may be inaccurate.."
```

2024-09-25 05:58 UTC, RanGojo commented on widget/embedded/src/pages/LanguagePage.tsx
> +          title="Warning: We are using machine translation, so the translations may not be very accurate."
fixed

2024-09-25 05:58 UTC, RanGojo commented on widget/embedded/src/components/Slippage/SlippageTooltipContent.tsx
> +          'This setting is applied to each individual step (e.g. 1Inch, Thorchain, etc.), meaning only that specific step will be reverted, not the entire route.'
done

2024-09-25 06:01 UTC, RyukTheCoder approved these changes
LGTM

2024-09-28 10:00 UTC, merged